# aws config
aws_s3_bucket: "belong-code-assessment-bonatoc"

# dev options
save_dataframe: true
load_dataframe: true

# io config
output_dir: "data"

# endpoint config
pedestrian_csv_url: "https://data.melbourne.vic.gov.au/api/views/b2ak-trbp/rows.csv?accessType=DOWNLOAD"
pedestrian_api_url: "https://data.melbourne.vic.gov.au/resource/b2ak-trbp.json"

# log config
log_dir: "logs"
log_level: "DEBUG"
